// Black Budget IDL — hand-written to match the Anchor program
// In production, this would be auto-generated by `anchor build`

export const IDL = {
  version: "0.1.0",
  name: "black_budget",
  instructions: [
    {
      name: "initializeCompany",
      accounts: [
        { name: "authority", isMut: true, isSigner: true },
        { name: "company", isMut: true, isSigner: false },
        { name: "vault", isMut: true, isSigner: false },
        { name: "usdcMint", isMut: false, isSigner: false },
        { name: "founderMember", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "name", type: "string" }],
    },
    {
      name: "addMember",
      accounts: [
        { name: "authority", isMut: true, isSigner: true },
        { name: "company", isMut: true, isSigner: false },
        { name: "authorityMember", isMut: false, isSigner: false },
        { name: "newMemberWallet", isMut: false, isSigner: false },
        { name: "member", isMut: true, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "role", type: { defined: "Role" } },
        { name: "label", type: "string" },
      ],
    },
    {
      name: "setPolicies",
      accounts: [
        { name: "authority", isMut: false, isSigner: true },
        { name: "company", isMut: true, isSigner: false },
        { name: "authorityMember", isMut: false, isSigner: false },
      ],
      args: [{ name: "policy", type: { defined: "PolicyConfig" } }],
    },
    {
      name: "createPayment",
      accounts: [
        { name: "requester", isMut: true, isSigner: true },
        { name: "company", isMut: true, isSigner: false },
        { name: "requesterMember", isMut: false, isSigner: false },
        { name: "recipient", isMut: false, isSigner: false },
        { name: "payment", isMut: true, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "amount", type: "u64" },
        { name: "category", type: { defined: "PaymentCategory" } },
        { name: "descriptionHash", type: { array: ["u8", 32] } },
        { name: "memo", type: "string" },
        { name: "riskScore", type: "u8" },
      ],
    },
    {
      name: "approvePayment",
      accounts: [
        { name: "approver", isMut: false, isSigner: true },
        { name: "company", isMut: false, isSigner: false },
        { name: "approverMember", isMut: false, isSigner: false },
        { name: "payment", isMut: true, isSigner: false },
      ],
      args: [],
    },
    {
      name: "rejectPayment",
      accounts: [
        { name: "rejector", isMut: false, isSigner: true },
        { name: "company", isMut: false, isSigner: false },
        { name: "rejectorMember", isMut: false, isSigner: false },
        { name: "payment", isMut: true, isSigner: false },
      ],
      args: [],
    },
    {
      name: "executePayment",
      accounts: [
        { name: "executor", isMut: true, isSigner: true },
        { name: "company", isMut: true, isSigner: false },
        { name: "executorMember", isMut: false, isSigner: false },
        { name: "payment", isMut: true, isSigner: false },
        { name: "vault", isMut: true, isSigner: false },
        { name: "recipientTokenAccount", isMut: true, isSigner: false },
        { name: "usdcMint", isMut: false, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
      ],
      args: [],
    },
  ],
  accounts: [
    { name: "Company", type: { kind: "struct", fields: [
      { name: "authority", type: "publicKey" },
      { name: "name", type: "string" },
      { name: "vault", type: "publicKey" },
      { name: "policy", type: { defined: "PolicyConfig" } },
      { name: "memberCount", type: "u8" },
      { name: "paymentNonce", type: "u64" },
      { name: "totalSpent", type: "u64" },
      { name: "monthlySpent", type: "u64" },
      { name: "currentMonth", type: "u8" },
      { name: "createdAt", type: "i64" },
      { name: "bump", type: "u8" },
    ]}},
    { name: "Member", type: { kind: "struct", fields: [
      { name: "company", type: "publicKey" },
      { name: "wallet", type: "publicKey" },
      { name: "role", type: { defined: "Role" } },
      { name: "label", type: "string" },
      { name: "addedAt", type: "i64" },
      { name: "isActive", type: "bool" },
      { name: "bump", type: "u8" },
    ]}},
    { name: "PaymentRequest", type: { kind: "struct", fields: [
      { name: "company", type: "publicKey" },
      { name: "requester", type: "publicKey" },
      { name: "recipient", type: "publicKey" },
      { name: "amount", type: "u64" },
      { name: "category", type: { defined: "PaymentCategory" } },
      { name: "descriptionHash", type: { array: ["u8", 32] } },
      { name: "memo", type: "string" },
      { name: "status", type: { defined: "PaymentStatus" } },
      { name: "approvals", type: { vec: "publicKey" } },
      { name: "requiredApprovals", type: "u8" },
      { name: "paymentId", type: "u64" },
      { name: "riskScore", type: "u8" },
      { name: "createdAt", type: "i64" },
      { name: "executedAt", type: "i64" },
      { name: "bump", type: "u8" },
    ]}},
  ],
  types: [
    { name: "PolicyConfig", type: { kind: "struct", fields: [
      { name: "autoApproveLimit", type: "u64" },
      { name: "dualApproveThreshold", type: "u64" },
      { name: "monthlyBurnCap", type: "u64" },
      { name: "requireVendorVerification", type: "bool" },
      { name: "restrictToKnownRecipients", type: "bool" },
      { name: "minRunwayMonths", type: "u8" },
    ]}},
    { name: "Role", type: { kind: "enum", variants: [
      { name: "Owner" }, { name: "Approver" }, { name: "Viewer" }, { name: "Contractor" },
    ]}},
    { name: "PaymentCategory", type: { kind: "enum", variants: [
      { name: "Payroll" }, { name: "Vendor" }, { name: "Subscription" },
      { name: "Contractor" }, { name: "Reimbursement" }, { name: "Other" },
    ]}},
    { name: "PaymentStatus", type: { kind: "enum", variants: [
      { name: "Pending" }, { name: "Approved" }, { name: "Executed" },
      { name: "Rejected" }, { name: "Cancelled" },
    ]}},
  ],
  errors: [],
} as const;

export const PROGRAM_ID = "3xgDaaFKmfGHBxhLfN16Eryyaact9fZ6tm6xypERpg9k";
